[package]
name = "zero85"
version = "0.2.0"
authors = ["H.Emre Yaren"]
repository = "https://github.com/emreyaren/zero85"
description = "Rust implementation of ZeroMQ's base85 algorithm."
license = "MIT/Apache-2.0"

[dev-dependencies]
quickcheck = "0.2.*"
